version: "3"
services:
  LeBonSandwich_prise_commande_api:
    container_name: LeBonSandwich_prise_commande_api
    image: node:17
    depends_on:
      - LeBonSandwich_db
    links:
      - LeBonSandwich_db
    env_file:
      - ./prise-commande/config/bdd.env
      - ./prise-commande/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./prise-commande:/usr/src/app
      - ./prise-commande/node_modules:/usr/src/app/node_modules
    ports:
      - ${EXPOSED_EXPRESS_PORT_PRISE_COMMANDE}:${EXPRESS_PORT}
    command: npm run watch
    networks:
      - LeBonSandwich

  LeBonSandwich_suivi_fabrication_api:
    container_name: LeBonSandwich_suivi_fabrication_api
    image: node:17
    depends_on:
      - LeBonSandwich_db
    links:
      - LeBonSandwich_db
    env_file:
      - ./suivi-fabrication/config/bdd.env
      - ./suivi-fabrication/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./suivi-fabrication:/usr/src/app
      - ./suivi-fabrication/node_modules:/usr/src/app/node_modules
    ports:
      - ${EXPOSED_EXPRESS_PORT_SUIVI_FABRICATION}:${EXPRESS_PORT}
    command: npm run watch
    networks:
      - LeBonSandwich
    
  LeBonSandwich_authentification_api:
    container_name: LeBonSandwich_authentification_api
    image: node:17
    depends_on:
      - LeBonSandwich_db
    links:
      - LeBonSandwich_db
    env_file:
      - ./authentification/config/bdd.env
      - ./authentification/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./authentification:/usr/src/app
      - ./authentification/node_modules:/usr/src/app/node_modules
    ports:
      - ${EXPOSED_EXPRESS_PORT_AUTHENTIFICATION}:${EXPRESS_PORT}
    command: npm run watch
    networks:
      - LeBonSandwich

  LeBonSandwich_adminer:
    container_name: LeBonSandwich_adminer
    image: adminer:4
    depends_on:
      - LeBonSandwich_db
    ports:
      - ${EXPOSED_ADMINER_PORT}:8080
    networks:
      - LeBonSandwich
  
  LeBonSandwich_db:
    container_name: LeBonSandwich_db
    image: mariadb:latest
    env_file:
      - ./database/config/bdd.env
    volumes:
      - ./db:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - LeBonSandwich


networks:
  LeBonSandwich:
    driver: bridge