version: "3"
services:
  LeBonSandwich_prise_commande_api:
    container_name: LeBonSandwich_prise_commande_api
    image: node:17
    depends_on:
      - LeBonSandwich_db
    links:
      - LeBonSandwich_db
    env_file:
      - ./prise-commande/config/bdd.env
      - ./prise-commande/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./prise-commande:/usr/src/app
      - ./prise-commande/node_modules:/usr/src/app/node_modules
    ports:
      - ${EXPOSED_EXPRESS_PORT_PRISE_COMMANDE}:${EXPRESS_PORT}
    command: npm run watch
    networks:
      - LeBonSandwich

  LeBonSandwich_suivi_fabrication_api:
    container_name: LeBonSandwich_suivi_fabrication_api
    image: node:17
    depends_on:
      - LeBonSandwich_db
    links:
      - LeBonSandwich_db
    env_file:
      - ./suivi-fabrication/config/bdd.env
      - ./suivi-fabrication/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./suivi-fabrication:/usr/src/app
      - ./suivi-fabrication/node_modules:/usr/src/app/node_modules
    ports:
      - ${EXPOSED_EXPRESS_PORT_SUIVI_FABRICATION}:${EXPRESS_PORT}
    command: npm run watch
    networks:
      - LeBonSandwich
    
  LeBonSandwich_authentification_api:
    container_name: LeBonSandwich_authentification_api
    image: node:17
    depends_on:
      - LeBonSandwich_db
    links:
      - LeBonSandwich_db
    env_file:
      - ./authentification/config/bdd.env
      - ./authentification/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./authentification:/usr/src/app
      - ./authentification/node_modules:/usr/src/app/node_modules
    command: npm run watch
    networks:
      - LeBonSandwich

  LeBonSandwich_gateway_api:
    container_name: LeBonSandwich_gateway_api
    image: node:17
    env_file:
      - ./gateway-front/config/service.env
      - ./gateway-front/config/server.env
    working_dir: /usr/src/app
    volumes:
      - ./gateway-front:/usr/src/app
      - ./gateway-front/node_modules:/usr/src/app/node_modules
    ports:
      - ${EXPOSED_EXPRESS_PORT_GATEWAY}:${EXPRESS_PORT}
    command: npm run watch
    networks:
      - LeBonSandwich


  cache:
    container_name: cache
    image: redis:6
    networks:
      - LeBonSandwich

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - LeBonSandwich_db
    env_file:
      - ./database/config/bdd.env
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: ${BDD_DRIVER}
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      - LeBonSandwich

  LeBonSandwich_adminer:
    container_name: LeBonSandwich_adminer
    image: adminer:4
    depends_on:
      - LeBonSandwich_db
    ports:
      - ${EXPOSED_ADMINER_PORT}:8080
    networks:
      - LeBonSandwich
  
  LeBonSandwich_db:
    container_name: LeBonSandwich_db
    image: mariadb:latest
    env_file:
      - ./database/config/bdd.env
    volumes:
      - ./db:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - LeBonSandwich


networks:
  LeBonSandwich:
    driver: bridge