name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 17.x]
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm ci
          cd prise-commande
          npm ci
          cd ../suivi-fabrication
          npm ci

  tsc-prise-commande:
    name: Typescript Compile Prise Commande
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: npm ci
        run: |
          npm ci
          cd prise-commande
          npm ci

      - name: Compile TypeScript
        run: |
          cd prise-commande
          tsc

  tsc-suivi-fabrication:
    name: Typescript Compile Suivi Fabrication
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: npm ci
        run: |
          npm ci
          cd suivi-fabrication
          npm ci

      - name: Compile TypeScript
        run: |
          cd suivi-fabrication
          tsc